version: '3.9'
services:
  app:
    container_name: devops-holiday-gingerbread-house
    env_file: .env
    restart: always
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true